const CONFIG = {
  store: {
    name:    "VELOCE",
    tagline: "Rodá diferente.",
    logo:    "",
    favicon: "",
    currency: "ARS",
    currencySymbol: "$",
    locale: "es-AR",
  },
  whatsapp: {
    number:  "+5491155550001",
    greeting: "¡Hola! 🚴 Quiero consultar sobre este pedido:\n\n",
    footer:   "\n\n¿Tienen disponibilidad para despacho esta semana?",
    floatingButton: true,
    checkoutButton: true,
  },
  theme: {
    scheme: "custom",
    custom: {
      "--color-bg":         "#0d0d0d",
      "--color-surface":    "#141414",
      "--color-border":     "#222222",
      "--color-text":       "#f5f5f5",
      "--color-text-muted": "#777777",
      "--color-primary":    "#f97316",
      "--color-accent":     "#f97316",
    },
    fontImport: "https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@400;600;700;900&family=Barlow:wght@400;500&display=swap",
    font:        "'Barlow', sans-serif",
    fontHeading: "'Barlow Condensed', sans-serif",
    borderRadius: "4px",
  },
  hero: {
    show: true,
    title: "La ruta te espera.",
    subtitle: "Bicicletas de competición, urbanas y MTB. Equipamiento de primer nivel.",
    image: "",
    cta: "Ver catálogo",
    ctaScroll: true,
  },
  nav: { showSearch: true, showCart: true, sticky: true },
  catalog: {
    showCategories: true, showSearch: true, defaultCategory: "Todos",
    productsPerRow: 3, showOutOfStock: true, outOfStockLabel: "Sin stock",
    addToCartLabel: "Agregar", showPriceOnCard: true,
    showSort: true, defaultSort: "featured",
  },
  promo: {
    show: true,
    layout: "alternating",
    heading: "",
    items: [
      {
        image:  "https://placehold.co/800x600/141414/f97316?text=RUTA+2026",
        label:  "Temporada 2026",
        title:  "La ruta te espera.",
        text:   "Nuestra línea de ruta combina aerodinámica y comodidad para recorridos de largo aliento. Cuadros de carbono T700 con geometría race o endurance.",
        cta:    "Ver bicicletas de ruta",
        ctaUrl: "#catalog",
      },
      {
        image:  "https://placehold.co/800x600/141414/f97316?text=MTB+PRO",
        label:  "Off-road",
        title:  "El sendero es tuyo.",
        text:   "MTB hardtail y full-suspension para todo tipo de terreno. Componentes seleccionados para resistir las condiciones más exigentes del trail.",
        cta:    "Ver MTB",
        ctaUrl: "#catalog",
      },
    ],
  },

  announcement: {
    show: true,
    items: [
      { icon: "🚚", title: "Envío a todo el país",   text: "Despachamos en 48–72hs hábiles por Andreani o OCA." },
      { icon: "🔧", title: "Armado incluido",        text: "Todas las bicicletas llegan armadas al 95%. Ajuste final en 5 min." },
      { icon: "🛡️", title: "Garantía 12 meses",     text: "Cuadro y componentes. Respaldados por el fabricante." },
      { icon: "💳", title: "Hasta 12 cuotas",        text: "Sin interés con tarjetas seleccionadas. Consultá por WhatsApp." },
    ],
    note: "Los precios pueden variar sin previo aviso. Las imágenes son ilustrativas. Stock sujeto a disponibilidad.",
  },
  cart: { persist: true, shippingNote: "Envío a todo el país. Se coordina por WhatsApp." },
  footer: {
    show: true,
    text: "",
    social: { instagram: "veloce.bikes", facebook: "", tiktok: "veloce.bikes" },
  },
};
